### ISSUE TITLE
Embed colors don't show

### ISSUE THREAD

**Issue by BayKedi** [L-Ratio/OperaGXTheme#11]
**Describe the bug**
Embed colors don't show

**To Reproduce**
1. Use theme
2. Spawn an embed

**Expected behavior**
A color surrounding the embed

**Screenshots**
![image](https://github.com/user-attachments/assets/ae4fdce6-ace2-4912-a078-4b789672c7ab)

**Desktop (please complete the following information):**
 - DiscordOS: betterdiscord
 - Browser Opera GX
 - Version 1.10.2

**Comment by L-Ratio** [comment]
fixed [5d6e767](https://github.com/L-Ratio/OperaGXTheme/commit/5d6e767b2995a95329d288c607dac061b069badb)
