### ISSUE TITLE
Exclamation Marks not rendering correctly

### ISSUE THREAD

**Issue by SynamoXV** [L-Ratio/OperaGXTheme#3]
Exclamation marks render as a lowercase 'l' when sent

when typing, the exclamation mark renders normally, but when the message is sent it turns into a lowercase 'l'

 - DiscordOS: [vencord and openasar in discord canary]

**Comment by L-Ratio** [comment]
Will not be fixing unless it becomes a problem on stable. I do not provide support for discord canary

**Comment by SynamoXV** [comment]
strangely enough, I switched to stable and it was fixed for a bit, but it is now an issue on normal/stable discord as well... might just be an issue with my computer though

**Comment by L-Ratio** [comment]
> strangely enough, I switched to stable and it was fixed for a bit, but it is now an issue on normal/stable discord as well... might just be an issue with my computer though.
> 
> edit: I fixed the issue by changing the font in the theme editor

Yeah I'm pretty sure it's with your computer as I do not have the problem on stable
