### ISSUE TITLE
Weird behavior when click on a channel with unread messages

### ISSUE THREAD

**Issue by chumbed10s** [L-Ratio/OperaGXTheme#4]
So, when u receive a message (ping or just a message) and when you go into that channel, the expected behavior would be "load the channel showing the first unread message" but it appears loading old messages, making it a bit tedious because you have to scroll down to the last message

**To Reproduce**
1. Receive a message in a channel or dm
2. Click in the channel/dm you get the message
3. You appear watching old messages in place of the first unread message

**Desktop (please complete the following information):**
 - DiscordOS: [betterdiscord]
 - Browser [Edge]
 - Version [113.0.1774.42 (Official build) (64-bit)]
 
 just to clarify, i uninstalled all the plugins and disabling the theme and the issue disappeared, i re enabled the theme but no pluglins and the issue came back so it's a theme issue

**Comment by L-Ratio** [comment]
I think I know what caused the problem [6acd9dc](https://github.com/L-Ratio/OperaGXTheme/commit/6acd9dce574ba4eec8a536716fdd2b1ed16cde96) should fix it

**Comment by chumbed10s** [comment]
Yeah it does, thank you a lot. Very good theme!
