### ISSUE TITLE
bug: everything is transparent

### ISSUE THREAD

**Issue by sI1vre** [L-Ratio/OperaGXTheme#5]
**Describe the bug**
almost everything is...unreadably transparent

**To Reproduce**
1. click on profile menu, hover over server, see unread icon, go to user options by right clicking on their profile picture

**Expected behavior**
it is not completely transparent

**Screenshots**
![bfHRyd8](https://github.com/L-Ratio/OperaGXTheme/assets/105620317/f7d35ef1-3f1f-4cbd-818f-d4dd946cf870)
![OL6lpAc](https://github.com/L-Ratio/OperaGXTheme/assets/105620317/43a5ead9-ff8a-486c-ab69-9d9fc2b2d8ff)
https://cdn.discordapp.com/attachments/1125869802955739136/1125870473914363934/lDirK4P.png

**Desktop (please complete the following information):**
 - DiscordOS: Vencord
 - Browser: Firefox

**Comment by L-Ratio** [comment]
You had the darker-background-color on transparent
