### ISSUE TITLE
Channel selector is gone

### ISSUE THREAD

**Issue by tryoutuser** [L-Ratio/OperaGXTheme#6]
**Describe the bug**
channel selector is gone from channel list, even for unread channels.

**To Reproduce**
apply the theme and check channel list

**Expected behavior**
selector should still there like before

**Screenshots**
![image](https://github.com/L-Ratio/OperaGXTheme/assets/35561383/a41c5350-1750-419e-ad97-3b94fac564ce)

**Desktop (please complete the following information):**
DiscordOS: betterdiscord v1.9.3
Stable 210901 (daacd72)
Host 1.0.9013 (34160)
Windows 10 64-Bit (10.0.19044)

**Comment by L-Ratio** [comment]
4fb0146 fixes it
