### ISSUE TITLE
bug: background image not showing on app

### ISSUE THREAD

**Issue by Tier6194** [L-Ratio/OperaGXTheme#8]
**Describe the bug**
background image isnt showing in any text channel or on members list but shows up fine everywhere else it normally shows up

**To Reproduce**
1. Go to 'any chat, server channel, basically any text channel'

**Expected behavior**
the background to show

**Screenshots**
![image](https://github.com/L-Ratio/OperaGXTheme/assets/79399685/4dfbafef-733f-4e8b-ab8e-1b212a076061)

**Desktop (please complete the following information):**
 - DiscordOS: [e.g. betterdiscord,goosemod] betterdiscord
 - Browser [e.g. chrome, safari] opera
 - Version [e.g. 22] ptb 237366

**Comment by JackoCatacomb** [comment]
discord itself might've fucked something up in a new update or something

**Comment by L-Ratio** [comment]
Should be fixed with 467bee9

**Comment by Kyberilium08** [comment]
It's not fixed. I have the same issue

**Comment by Kyberilium08** [comment]
oh nevermind, I used incorrect syntax
